#!/bin/bash

# This script cleans all the data generated when running the `execute_calculations_lite.sh`.
# For the B0 Integral Study, the file a specific file is not generated by the calculations 
# script and it must be stored befored deleting all the files with suffix *.dat

cd ../.. || exit

# B0 Integral Study
filename=B0_vs_k0_T0p0Cpi0p0Cpj0p0L1p0Mi0p4Mj0p4k0p0_k0Shift
cp calculations/two_fermion_line_integral_3d_cutoff/data/${filename}.dat calculations/two_fermion_line_integral_3d_cutoff/data/${filename}.bak
rm -rf calculations/two_fermion_line_integral_3d_cutoff/data/*.dat
cp calculations/two_fermion_line_integral_3d_cutoff/data/${filename}.bak calculations/two_fermion_line_integral_3d_cutoff/data/${filename}.dat
rm calculations/two_fermion_line_integral_3d_cutoff/data/${filename}.bak

# SU3 NJL Vacuum Study with and without 8q interactions
rm -rf calculations/su3_3d_cutoff_vacuum_masses/data/*.dat

# SU3 NJL Phase Diagram Study with and without 8q interactions
rm -rf calculations/su3_3d_cutoff_phase_diagram/data/*.dat

# SU3 NJL Cross Section Study with Klevansky parameter set
rm -rf calculations/su3_3d_cutoff_cross_sections_klevansky/data/*.dat

# SU3 NJL Thermodynamics Study with and without 8q interactions
rm -rf calculations/su3_3d_cutoff_thermodynamics/fixed_chem_pot_temp/data/*.dat

# SU3 NJL Integrated Cross Section Study
rm -rf calculations/su3_3d_cutoff_int_cross_sections/zero_chem_pot/data/*.dat

# SU3 NJL Quark Relaxation Time Study
rm -rf calculations/su3_3d_cutoff_quark_relaxation_times/data/*.dat

# SU3 NJL Transport Coefficients Study
rm -rf calculations/su3_3d_cutoff_transport_coefficients/data/*.dat
